### ISSUE TITLE
std::bad_alloc

### ISSUE THREAD

**Issue by DADA30000** [DreamMaoMao/hyev#1]

**Comment by DreamMaoMao** [comment]
I have not encountered any problems, can you provide more detailed information, like hyprland version, and run log

**Comment by DADA30000** [comment]
How can I get a run log?

**Comment by DADA30000** [comment]
Oh, um, I'm really sorry, it's a really dumb mistake, i've looked into logs, saw that it is executing a command, than i tried to look up what is that "play" command, installed sox package, and boom, it's working, sorry again for the trouble...
